name: Build & Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: immich-3ds
          path: immich-3ds.3dsx
